services:
  - postgresql

language: node_js

node_js:
  - v9.11.2

before_script:
  - psql -c "CREATE DATABASE users_tests;" -U postgres
  - psql -c "CREATE USER coder WITH PASSWORD 'pg123';" -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-server-dev-10