language: node_js

node_js:
  - v9.11.2

before_script:
  - psql -c 'create database  users_tests;' -U postgres




env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_products_tests




addons:
    apt:
    packages:
    - postgresql-server-dev-9.2