services:
  - postgresql

language: node_js

node_js:
  - v9.11.2

before_script:
  - cp config/database.yml.travis config/database.yml

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/users_tests

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2


