
language: node_js
node_js:
  - v9.11.2
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/users_tests

before_script:
  - psql -c 'create database users_tests' -U postgres
  - psql -U postgres -d users_tests -a -f greetings.sql
